---
functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
    
non-functional:
  - Сайт должен иметь мобильную версию
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы    
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика    
  - Сайт должен быть доступен на различных устройствах

implicit:
  - шрифт текста должен быть четко виден
  - в описании товара должны быть указаны характеристики
  - в карточке товара должны быть соответствующие фотографии 
  - фильтры должны отображать товары по выбранным категориям
  - категории товаров должны быть видны в карточках товаров


   
